//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_CT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aluno()
        {
            this.graduacaoAluno = new HashSet<graduacaoAluno>();
        }
    
        public int idAluno { get; set; }
        public string nome { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public System.DateTime data_nascimento { get; set; }
        public string endereco { get; set; }
        public string planoSaude { get; set; }
        public string numeroAluno { get; set; }
        public string numeroParente { get; set; }
        public byte[] foto { get; set; }
        public System.DateTime dataPagamento { get; set; }
        public int idTipoMatricula { get; set; }
        public int idUsuario { get; set; }
    
        public virtual tipoMatricula tipoMatricula { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<graduacaoAluno> graduacaoAluno { get; set; }
    }
}
