//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_CT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class graduacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public graduacao()
        {
            this.graduacaoAluno = new HashSet<graduacaoAluno>();
        }
    
        public int idGraduacao { get; set; }
        public string corGraduacao { get; set; }
        public int idUsuario { get; set; }
    
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<graduacaoAluno> graduacaoAluno { get; set; }
    }
}
