//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_CT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class graduacaoAluno
    {
        public int idAluno { get; set; }
        public int idGraduacao { get; set; }
        public System.DateTime dataGraduacao { get; set; }
    
        public virtual aluno aluno { get; set; }
        public virtual graduacao graduacao { get; set; }
    }
}
