//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_CT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoMatricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipoMatricula()
        {
            this.aluno = new HashSet<aluno>();
        }
    
        public int idTipoMatricula { get; set; }
        public string nomeTipo { get; set; }
        public int idUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluno> aluno { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
